[features]
seeds = false
skip-lint = false
[programs.localnet]
vaulter = "VA1Ley3XMKGbtUx2MukbBiErRgD2UKLRoWPxooP7aKY"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/lando/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
